### ISSUE TITLE
Please specify the license.

### ISSUE THREAD

**Issue by michilu** [yfuruyama/stackdriver-request-context-log#1]
Hi, guys.

It seems to have some problems because it has no specific license.
- There is a risk of import the module that no specific license.
- Could not see documents on [stackdriver package · go\.dev](https://pkg.go.dev/github.com/yfuruyama/stackdriver-request-context-log?tab=doc)

Thanks.

**Comment by yfuruyama** [comment]
Thanks for reporting the issue.

I just added the LICENSE file (Apache 2.0) and generated godoc for this package.
https://godoc.org/github.com/yfuruyama/stackdriver-request-context-log

I will close this issue, but let me know if you have any questions.
